### PR TITLE
(chore) Update the k8s dependencies to v0.18.2

### PR DESCRIPTION
**Pull request by rahulchheda**
Signed-off-by: Rahul M Chheda <rchheda@infracloud.io>

**What this PR does / why we need it**:

- Upgraded the operator-sdk version & k8s deps to v0.18.2.
- Apart from that, need to make some new fixes i.e
    - Removed the replace target for some deps in go.mod (@rajdas98)
    - To upgrade operator-sdk, we need to add context to all the client-go calls, done this according to this ref: https://sdk.operatorframework.io/docs/upgrading-sdk-version/v0.18.0/#kubernetes-client-go-contexts
    - Added `-mod=vendor` floag which doing go build which make more sense. (@rajdas98)
    - Some linting issues were auto corrected.

**TODO**:
- Had to change flags for stopping `golint` to report errors in vendor dir. (@ksatchit @chandankumar4)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] Labelled this PR & related issue with `documentation` tag
-   [ ] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests

### CODE REVIEW

**Comment by rajdas98** [comment]
Can you upgrade to the latest version? Also, if possible can you remove the vendor ?

**Comment by rahulchheda** [comment]
@ksatchit Could we get this in the latest release? I will fix CI in a while.

**Comment by rahulchheda** [comment]
@rajdas98 I think v0.17, or v0.18 would be okish. WDYT? @ksatchit

**Comment by rahulchheda** [comment]
Is their a specific reason for deleting the `vendor` folder @rajdas98 ?

**Comment by immanetize** [comment]
> Is their a specific reason for deleting the `vendor` folder @rajdas98 ?

I was going to comment on this as well.  As I understand it, `go` will populate the vendor/ directory based on dependencies declared in go.mod; their presence is reproducible.  While go would compile these libraries into any final deliverable, I do not think it is necessary or helpful to maintain their sources in the code repository for this separate project.  Is there a specific reason to have the vendor folder committed that I'm not aware of?

**Comment by ksatchit** [comment]
@rahulchheda @rajdas98 these are good changes. However, I would soak them for a while with e2e with pipeline runs, before taking them into a 1.9.x patch release.

**Comment by rahulchheda** [comment]
> > Is their a specific reason for deleting the `vendor` folder @rajdas98 ?
> 
> I was going to comment on this as well. As I understand it, `go` will populate the vendor/ directory based on dependencies declared in go.mod; their presence is reproducible. While go would compile these libraries into any final deliverable, I do not think it is necessary or helpful to maintain their sources in the code repository for this separate project. Is there a specific reason to have the vendor folder committed that I'm not aware of?

Yes, their is no need to maintain the vendor folder. I think we can remove it. Let me do that, so that we can merge this.

**Comment by ksatchit** [comment]
> > Is their a specific reason for deleting the `vendor` folder @rajdas98 ?
> 
> I was going to comment on this as well. As I understand it, `go` will populate the vendor/ directory based on dependencies declared in go.mod; their presence is reproducible. While go would compile these libraries into any final deliverable, I do not think it is necessary or helpful to maintain their sources in the code repository for this separate project. Is there a specific reason to have the vendor folder committed that I'm not aware of?

Seems to be a general practice not to push vendor to git (the go.mod is sufficient and vendor can be recreated from this) - though we have been maintaining vendor folders on all repos thus far. We could go one step further and dockerize the build itself - that way we will cut down on the differences in build env even more efficiently. Many projects are adopting this approach.

**Comment by rajdas98** [comment]
The reason of upgrading go to v0.18.x because we are using some chaos operator pkg in the subscriber of litmus-portal. All components of litmus-portal are using v0.18.3 expect subscriber, which is having same version as operator.

**Review by chandankumar4 — COMMENTED** [review]
All looks good, if we just resolve the conflict!!
Thanks for upgrading, Might be it require some good amount of testing after going to master.

**Comment by ispeakc0de** [comment]
https://github.com/litmuschaos/chaos-operator/pull/411

**Pull request closed without merging**
