### PR TITLE
[Feat.] Add JobCleanUpPolicy field in ChaosEngine schema

### PR DESCRIPTION
**Pull request by rahulchheda**
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>

**What this PR does / why we need it**:

- This schema introduces the capability to retain or delete completed experiment jobs in the application namespace. 
- The business logic for this is implemented via the chaos executor at https://github.com/litmuschaos/litmus/pull/854

**Which issue this PR fixes** : https://github.com/litmuschaos/litmus/issues/857

**Special notes for your reviewer**:

**Checklist:**
- [ ] Fixes #<issue number>
- [ ] Labelled this PR & related issue with `documentation` tag
- [ ] PR messages has document related information
- [ ] Labelled this PR & related issue with `breaking-changes` tag
- [ ] PR messages has breaking changes related information
- [ ] Labelled this PR & related issue with `requires-upgrade` tag
- [ ] PR messages has upgrade related information
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Comment by rahulchheda** [comment]
##New schema has to look like this:
```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
  namespace: litmus 
spec:
  jobCleanUpPolicy: retain 
  appinfo: 
    appns: litmus
    # FYI, To see app label, apply kubectl get pods --show-labels
    applabel: "app=hello-deployment" 
  chaosServiceAccount: litmus 
  experiments:
    - name: pod-delete

```

**Comment by chandankumar4** [comment]
@rahulchheda After changing the schema of `ChaosEngineSpec` have you try to generate the auto-generated file, Like you have to run these:
- operator-sdk generate k8s
- ./hack/update-codegen.sh

**Comment by chandankumar4** [comment]
Can you paste the output of:
```
cd ${GOPATH}/src/k8s.io/code-generator/
git branch
```

**Comment by rahulchheda** [comment]
```
rahul@rahul-ThinkPad-E490:~/go-dev/src/github.com/litmuschaos/chaos-operator$ ./hack/update-codegen.sh 
Generating clientset for litmuschaos:v1alpha1 at github.com/litmuschaos/chaos-operator/pkg/client/clientset
Generating listers for litmuschaos:v1alpha1 at github.com/litmuschaos/chaos-operator/pkg/client/listers
Generating informers for litmuschaos:v1alpha1 at github.com/litmuschaos/chaos-operator/pkg/client/informers
```

**Comment by rahulchheda** [comment]
git branch
```
rahul@rahul-ThinkPad-E490:~/go-dev/src/github.com/litmuschaos/chaos-operator$ git branch
* delete_job
  master
```

**Comment by rahulchheda** [comment]
cd ${GOPATH}/src/k8s.io/code-generator/
ls
```
rahul@rahul-ThinkPad-E490:~/go-dev/src/github.com/litmuschaos/chaos-operator$ ./hack/update-codegen.sh 
Generating clientset for litmuschaos:v1alpha1 at github.com/litmuschaos/chaos-operator/pkg/client/clientset
Generating listers for litmuschaos:v1alpha1 at github.com/litmuschaos/chaos-operator/pkg/client/listers
Generating informers for litmuschaos:v1alpha1 at github.com/litmuschaos/chaos-operator/pkg/client/informers
rahul@rahul-ThinkPad-E490:~/go-dev/src/github.com/litmuschaos/chaos-operator$ cd ${GOPATH}/src/k8s.io/code-generator/
rahul@rahul-ThinkPad-E490:~/go-dev/src/k8s.io/code-generator$ ls
cmd                 CONTRIBUTING.md  generate-groups.sh           Godeps  go.sum  LICENSE  pkg        SECURITY_CONTACTS  tools.go
code-of-conduct.md  _examples        generate-internal-groups.sh  go.mod  hack    OWNERS   README.md  third_party
```

**Comment by rahulchheda** [comment]
@chandankumar4 @ksatchit Changed the ./hack/update-codegen.sh to use the k8s.io/code-generator from the vendor itself rather than the local go src PTAL!

**Comment by ksatchit** [comment]
So, is this the recommended auto-genetation procedure ? Trying to set the right expectations for future PRs

**Comment by chandankumar4** [comment]
> So, is this the recommended auto-genetation procedure ? Trying to set the right expectations for future PRs

Yes, After changing anything to api we have to run these once
```
operator-sdk generate k8s
./hack/update-codegen.sh
```

**Pull request merged**
