### PR TITLE
(UT): GetChaosRunnerENV Unit Test Cases

### PR DESCRIPTION
**Pull request by sureshpathipati**
Issue fixed: https://github.com/litmuschaos/litmus/issues/769

@chandankumar4 
Plz review

### CODE REVIEW

**Comment by sureshpathipati** [comment]
@chandankumar4 
Need your help in fixing this.
I hope my changes are nothing to do with this.

Screen Shot 2019-10-21 at 10 02 53 AM

Plz do correct me, if my understanding is not correct.

**Comment by chandankumar4** [comment]
> @chandankumar4
> Need your help in fixing this.
> I hope my changes are nothing to do with this.
> 
> Screen Shot 2019-10-21 at 10 02 53 AM
> 
> Plz do correct me, if my understanding is not correct.

This error is not causing the lint failed, Can you check the circle-ci build log

**Comment by sureshpathipati** [comment]
@chandankumar4 
Thank you.
Updated accordingly.

**Comment by sureshpathipati** [comment]
@chandankumar4 
Plz review

**Comment by sureshpathipati** [comment]
@chandankumar4 
Plz review

**Pull request merged**
