### PR TITLE
Unit test case for add()

### PR DESCRIPTION
**Pull request by ryand91**
Unit test for add()

(chaos-operator): Add unit test cases for function add() fixes #771

### CODE REVIEW

**Comment by chandankumar4** [comment]
Thanks @ryand91 for your contribution, Can you resolve the conflict

**Comment by ryand91** [comment]
Hi @chandankumar4 yes I'm trying to resolve the conflict.

**Comment by chandankumar4** [comment]
@ryand91 After resolving the conflict there is some issue with the build, Please have a look

**Comment by chandankumar4** [comment]
Closing this stale PR, You can reopen it anytime

**Pull request closed without merging**
